CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS events
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    admin_id BIGINT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_users
(
    events_id BIGINT NOT NULL,
    users_id  BIGINT NOT NULL,
    CONSTRAINT pk_events_users PRIMARY KEY (events_id, users_id)
);

CREATE TABLE IF NOT EXISTS tasks
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    event_id BIGINT,
    user_id  BIGINT,
    state    VARCHAR(255),
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);
